// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEwQB8QqFmV5XNteT8M01aZ04p_ST8Dog',
    appId: '1:472951246345:android:913a8e5816a1a2823c72d8',
    messagingSenderId: '472951246345',
    projectId: 'travelsocialapp-8f61a',
    storageBucket: 'travelsocialapp-8f61a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs4yQ64inx-etHpfcSB5DbezOa1PW9SaU',
    appId: '1:472951246345:web:d85ca0596853f6813c72d8',
    messagingSenderId: '472951246345',
    projectId: 'travelsocialapp-8f61a',
    authDomain: 'travelsocialapp-8f61a.firebaseapp.com',
    storageBucket: 'travelsocialapp-8f61a.firebasestorage.app',
    measurementId: 'G-KBDZ2XTT6R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsG5gk45bbLOQy6Pn0tIBy6qouh3Ohhi8',
    appId: '1:472951246345:ios:d76e7189492528373c72d8',
    messagingSenderId: '472951246345',
    projectId: 'travelsocialapp-8f61a',
    storageBucket: 'travelsocialapp-8f61a.firebasestorage.app',
    androidClientId:
        '472951246345-92lij6lffeaigfj3f2uceddpskbie22s.apps.googleusercontent.com',
    iosClientId:
        '472951246345-qa11g38fu1qihl862gth9vlalpmbiff6.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelSocialApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsG5gk45bbLOQy6Pn0tIBy6qouh3Ohhi8',
    appId: '1:472951246345:ios:d76e7189492528373c72d8',
    messagingSenderId: '472951246345',
    projectId: 'travelsocialapp-8f61a',
    storageBucket: 'travelsocialapp-8f61a.firebasestorage.app',
    androidClientId:
        '472951246345-92lij6lffeaigfj3f2uceddpskbie22s.apps.googleusercontent.com',
    iosClientId:
        '472951246345-qa11g38fu1qihl862gth9vlalpmbiff6.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelSocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs4yQ64inx-etHpfcSB5DbezOa1PW9SaU',
    appId: '1:472951246345:web:183ce6027eafadf73c72d8',
    messagingSenderId: '472951246345',
    projectId: 'travelsocialapp-8f61a',
    authDomain: 'travelsocialapp-8f61a.firebaseapp.com',
    storageBucket: 'travelsocialapp-8f61a.firebasestorage.app',
    measurementId: 'G-LP8WP4WD8Y',
  );
}
